---
- name: create polkadot service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/{{ chain_stub }}.service
    owner: root
    group: root
    mode: 0600

- name: restart polkadot service
  systemd:
    name: "{{ chain_stub }}.service"
    enabled: yes
    state: restarted
    daemon_reload: yes
  changed_when: false
  when: polkadot_service_running.stdout == "no"

- name: polkadot session management
  include_tasks: session.yml